// Generated by scripts/generate-corpus-module.mjs from fixtures/versions.
// Edit the fixture and regenerate; do not edit this file.

import type { VersionCorpus } from '../corpus-types.js';
import { CRATES_IO_CORPUS } from './crates-io.js';
import { GO_CORPUS } from './go.js';
import { MAVEN_CORPUS } from './maven.js';
import { NPM_CORPUS } from './npm.js';
import { PYPI_CORPUS } from './pypi.js';

/** Every comparator corpus, ordered by ecosystem so the digest is stable. */
export const ALL_CORPORA: readonly VersionCorpus[] = [
  CRATES_IO_CORPUS,
  GO_CORPUS,
  MAVEN_CORPUS,
  NPM_CORPUS,
  PYPI_CORPUS,
];
