// Generated by scripts/generate-corpus-module.mjs from fixtures/versions.
// Edit the fixture and regenerate; do not edit this file.

import type { VersionCorpus } from '../corpus-types.js';

export const GO_CORPUS: VersionCorpus = {
  ecosystem: "Go",
  comparator: "go",
  reference: "golang.org/x/mod/semver rules with the OSV spelling that omits the v, ordered with node-semver 7.8.5 after expanding the prefix and the implied minor and patch",
  ordered: [
    "v0.0.0-20191109021931-daa7c04131f5",
    "v0.0.0-20210226172049-e18ecbb05110",
    "v0.0.0",
    "v0.0.1",
    "v0.1.0",
    "v0.9.0",
    "v0.10.0",
    "v0.22.0",
    "v0.23.0",
    "v1",
    "v1.0.1",
    "v1.1",
    "v1.2.3-0.20200101000000-abcdef123456",
    "v1.2.3-rc.1",
    "v1.2.3",
    "v1.9.0",
    "v1.10.0",
    "v2.0.0-rc.1",
    "v2.0.0",
    "v2.1.0",
    "v3.0.0",
  ],
  equal: [
    ["v1.0.0", "v1"],
    ["v1.2.0", "v1.2"],
    ["v2.0.0", "v2.0.0+incompatible"],
    ["v1.0.0+a", "v1.0.0+b"],
    ["v1.2.3", "1.2.3"],
    ["v0.22.0", "0.22.0"],
    ["v1", "1.0.0"],
  ],
  invalid: [
    "v1.0.0-",
    "v01.0.0",
    "",
    "latest",
    "v",
    "master",
    "v1.0.0.0",
  ],
};
